installation:
  mode: project-development
  detected_at: '2026-01-29T23:57:33.958Z'
repository:
  url: https://github.com/emilyveigaai/aios-core.git
  auto_detect: true
framework:
  source: npm
  version: 3.10.0
  location: /Users/emilyveiga/code/aios-core-fork
git_ignore_rules:
  mode: project-development
  ignore_framework_files: true
